apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000         # Service port
      targetPort: 5000   # Flask container port
      nodePort: 31500    # Optional (you can omit this to let Kubernetes assign automatically)
