name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t steven0707/flaskapp:${{ github.sha }} .
          docker push steven0707/flaskapp:${{ github.sha }}

      - name: Start Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=docker

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s-manifests/
          kubectl set image deployment/flask-deployment flask-app=steven0707/flaskapp:${{ github.sha }}
          kubectl rollout status deployment/flask-deployment

      - name: Verify Deployment
        run: kubectl get pods -o wide
